name: Go CI

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Lint and Test Go Code
    runs-on:
      - ubuntu-latest
    env:
      GOPRIVATE: github.com/gateway-fm/generic-rpc
      GO111MODULE: on
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # Required by golangci-lint, according to docs
      - name: Setup Golang Environment
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Configure git for private modules
        if: env.GOPRIVATE != ''
        env:
          TOKEN: ${{ secrets.PROXY_PIPELINES_GITHUB_TOKEN }}
        run: git config --global url."https://oauth2:${TOKEN}@github.com/gateway-fm".insteadOf "https://github.com/gateway-fm"

      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.52
          skip-cache: true
          skip-build-cache: true
          skip-pkg-cache: true
          args: --timeout=10m

      - name: run tests and generate coverage
        run: go test ./... -coverprofile=./cover.out

      - name: check test coverage
        id: coverage ## this step must have id
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: cover.out
          local-prefix: microservice-template
          threshold-file: 0
          threshold-package: 0
          threshold-total: 0

      - name: make coverage badge
        uses: action-badges/core@0.2.2
        if: contains(github.ref, 'main')
        with:
          label: coverage
          message: ${{ steps.coverage.outputs.badge-text }}
          message-color: ${{ steps.coverage.outputs.badge-color }}
          file-name: coverage.svg
          badge-branch: badges ## orphan branch where badge will be committed
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Clean workspace
        uses: AutoModality/action-clean@v1.1.0

  release:
    name: Make Release
    needs:
      - test
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.RELEASES_ACTION_GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          token: ${{ secrets.RELEASES_ACTION_GITHUB_TOKEN }}
